### ISSUE TITLE
support custom ctag generator for different file types

### ISSUE THREAD

**Issue by hatelove85911** [still-dreaming-1/vim-project-tags#2]
thanks for the great idea and plugin. 

the feature that I want most is that for js files, I can use `jsctags` to generate tags. and for others I can use ctags. 

based on the current feature of the plugin, I think what would make this plugin perfect is:
1. support custom ctag generator for different file types.
2. as mentioned in the readme, in C programing, user wants to combind the tags for `.c` and `.h` files. So please consider to support tag file generation by grouping file types. meaning user could specify a group of file type, like ['.c', '.h'], and then one tag file will be generated for these two file types.
3. in the above grouping file type case, still allow user to appoint different ctag generator for different file types.
4. [gutentag ](https://github.com/ludovicchabant/vim-gutentags) like automatic tag generation management.

**Comment by still-dreaming-1** [comment]
I appreciate the input. What do you like about jsctags? I have never heard of it it before. Currently I am using [universal ctags](https://ctags.io), which does generate javascript tags. But now you have got me curious about `jsctags`

**Comment by hatelove85911** [comment]
[jsctags](https://github.com/ramitos/jsctags) is based [tern.js ](https://github.com/ternjs/tern)which does a better job parsing modern javascript code than others. 

I don't know about universal ctags before, thanks for pointing out. I'll have a look at it. But I think currently, `jsctags` will still be the best tag generator for modern javascript.

**Comment by still-dreaming-1** [comment]
Thanks for the info. It is a good idea to be able to customize the ctags path in more than just a global setting, which is the current option. I might try out jsctags.

I was under the impression different tag generators don't typically make a huge difference because at the end of the day the biggest limitation comes from the fact that you are using tags inside Vim. In Vim when your definition lookup or code completion rely on tags, Vim does not take into account the context from which you are using them. So any matching tag seems like a valid match even if tern knows of a better match. So some of deeper understanding that tern has will be lost in the context of using tags inside Vim.

It still might produce better tags, and even a small improvement is better than nothing. You might also want to try out [Tern for vim](https://github.com/ternjs/tern_for_vim). I have not tried it yet. It uses tern directly instead of tags, so it should get around the limitations of tags and take full advantage of tern. Have you tried it?

**Comment by still-dreaming-1** [comment]
I am curious to know if you have tried out Tern for Vim? Do you still have an interest in using tags for javascript code instead of Tern for Vim?

**Comment by hatelove85911** [comment]
@still-dreaming-1 , I haven't got the time to try it out. Originally I installed tern for vim just because tagbar recommended. Never thought use it independently. I'll get back to you once I tried it out.
